package Utils;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.Map.Entry;

import sqls.EmployeeSQLConstants;

import sqls.EmployeeSQLConstants;

public class CYCSpecificMethodsUtil {

	String EmpSSN;
	String SQL;
	String EmpLastName;
	String PartnerEmpID;
	
	synchronized public String autoGeneratedFeed(String Key) throws SQLException {
		
		String Value = null;
		boolean Unique_Value_Found = false;
		boolean Unique_LastName_Found = false;
		String QueryResult_Out="";
		
		switch (Key) {
		case "Account SSN":
			System.out.println("inside switch "+Key);
			while(!Unique_Value_Found) {
				EmpSSN = ReusableMethodsUtil.randomNumberLengthbased(9);
				SQL = EmployeeSQLConstants.CHECK_UNIQUE_SSN.replace("$SubsSSN$", EmpSSN);
				ArrayList<Map<Object, Object>> queryResult = DataBaseUtil.storeDBResultSet(SQL);
				
				for(Map<Object,Object> mapEntry:queryResult) {
					for(Entry<Object, Object> map :mapEntry.entrySet()) {
						QueryResult_Out = map.getValue().toString();						
					}
				}
								
				if(QueryResult_Out.equals("0")) {
					Unique_Value_Found = true;
				}				
			}
			Value = EmpSSN;
			break;
		case "Last Name":
			
			while(!Unique_LastName_Found) {
				EmpLastName = "SELENIUM" + ReusableMethodsUtil.randomNumberLengthbased(6); 
				SQL= EmployeeSQLConstants.CHECK_UNIQUE_LASTNAME.replace("$LASTNAME$", EmpLastName);
				ArrayList<Map<Object, Object>> queryResult = DataBaseUtil.storeDBResultSet(SQL);
				
				for(Map<Object, Object> mapValues:queryResult) {
					for(Entry<Object, Object> map: mapValues.entrySet()) {
						QueryResult_Out=map.getValue().toString();
					}
					
				}
				
				if(QueryResult_Out.equals("0")) {
					Unique_LastName_Found= true;
				}
			}
			
			Value = EmpLastName;			
			break;
			
		case "Partner Employee ID":
			
			while(!Unique_Value_Found) {
				PartnerEmpID = ReusableMethodsUtil.randomNumberLengthbased(9); 
				SQL= EmployeeSQLConstants.CHECK_UNIQUE_PARTNER_EMPLOYER_ID.replace("$Partner_ID$", PartnerEmpID);
				ArrayList<Map<Object, Object>> queryResult = DataBaseUtil.storeDBResultSet(SQL);
				
				for(Map<Object, Object> mapValues:queryResult) {
					for(Entry<Object, Object> map: mapValues.entrySet()) {
						QueryResult_Out=map.getValue().toString();
					}
					
				}
				
				if(QueryResult_Out.equals("0")) {
					Unique_Value_Found= true;
				}
			}
			
			Value = "P"+PartnerEmpID;			
			break;
		default:
			break;
		}
		
		return Value;
	}
}

