package Utils.Employee;

import java.sql.SQLException;
import java.util.HashMap;

import Utils.CYCSpecificMethodsUtil;
import Utils.CsvUtil;
import Utils.DateTimeUtil;
import Utils.ExcelDataUtil;

public class EmployeeLoadUtil {
	
	CYCSpecificMethodsUtil cycSpecificMethodsUtil;
	
	public EmployeeLoadUtil() {
		cycSpecificMethodsUtil = new CYCSpecificMethodsUtil();
	}

	public void generateDataNewHire(String scenarioId, String InputSheet, String OutputSheet) throws Exception {
		
		String temp="";
		ExcelDataUtil dataUtil= new ExcelDataUtil(scenarioId, InputSheet);
		HashMap<String, String> FieldValues = dataUtil.getFieldValues();
		System.out.println(FieldValues);
		
		for(String Key: FieldValues.keySet()) {
			String FieldValue =FieldValues.get(Key);
			if(FieldValue !=null) {
				if(FieldValue.isEmpty()== false) {
					if(FieldValue != "") {
						if(FieldValue.substring(0,1).equalsIgnoreCase("#")) {
							if(FieldValue.contains("Auto_Generated")) {
								System.out.println(Key);
								temp = cycSpecificMethodsUtil.autoGeneratedFeed(Key);
								System.out.println("Autogenerated content is "+temp);
							} else if (FieldValue.contains("Date")) {
								temp = DateTimeUtil.generateDateUsingParsePath(FieldValue, "Date:MM/DD/CCYY");
								System.out.println("formatted Date is "+temp);
							} else if (FieldValue.contains("ParsePath")) {
								temp = CsvUtil.readDataUsingParsedPath(FieldValue);
								System.out.println(temp);
							}
						}else {
							temp = FieldValue;
						}
					}
				} else if(FieldValue.isEmpty() == true) {
					temp = FieldValue;
				}
			} else {
				temp = FieldValue;
			}
			ExcelDataUtil dataUtil_update= new ExcelDataUtil(scenarioId, OutputSheet);
			dataUtil_update.updateTheFieldValues(Key,temp);
			
		}
	}
}
